# Generated by Django 5.2 on 2025-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('last_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('has_changes', models.BooleanField(default=False)),
                ('marked_done', models.BooleanField(default=False)),
            ],
        ),
    ]
